services:
  frpc:
    image: snowdreamtech/frpc:latest
    command: ["-c", "/etc/frp/frpc.toml"]
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml:ro
      - ../certs/client/client.crt:/etc/frp/certs/client.crt:ro
      - ../certs/client/client.key:/etc/frp/certs/client.key:ro
      - ../certs/FRP_CA.crt:/etc/frp/certs/CA.crt:ro
    networks: [frpnet]
  
  backend:
    image: mendhak/http-https-echo:29
    environment:
      - HTTP_PORT=8080
      - HTTPS_PORT=0
    networks: [frpnet]

networks:
  frpnet:
    name: frpnet
    external: true
